const operations:Operations = {
    SQL: "sql",
    SYSTEM_INFORMATION: "system_information",
    CLUSTER_STATUS: "cluster_status",
    ADD_NODE: "add_node",
    UPDATE_NODE: "update_node",
    REMOVE_NODE: "remove_node",
    DESCRIBE_ALL: "describe_all",
    CREATE_SCHEMA: "create_schema",
    DESCRIBE_SCHEMA: "describe_schema",
    DROP_SCHEMA: "drop_schema",
    CREATE_TABLE: "create_table",
    DESCRIBE_TABLE: "describe_table",
    DROP_TABLE: "drop_table",
    SEARCH_BY_VALUE: "search_by_value",
    SEARCH_BY_HASH: "search_by_hash",
    SEARCH_BY_CONDITIONS: "search_by_conditions",
    CSV_DATA_LOAD: "csv_data_load",
    CSV_URL_LOAD: "csv_url_load",
    CSV_FILE_LOAD: "csv_file_load",
    INSERT: "insert",
    UPDATE: "update",
    DELETE: "delete",
    IMPORT_FROM_S3: "import_from_s3",
    EXPORT_TO_S3: "export_to_s3",
    EXPORT_LOCAL: "export_local",
    ADD_USER: "add_user",
    ALTER_USER: "alter_user",
    DROP_USER: "drop_user",
    LIST_USERS: "list_users",
    LIST_ROLES: "list_roles",
    ALTER_ROLE: "list_role",
    ADD_ROLE: "add_role",
    READ_TRANSACTION_LOG: "read_transaction_log",
    DELETE_TRANSACTION_LOGS: "delete_transaction_logs_before",
    DELETE_RECORDS_BEFORE: "delete_records_before",
    READ_LOG: "read_log",
    GET_JOB: "get_job",
    CREATE_AUTHENTICATION_TOKENS: "create_authentication_tokens",
    REFRESH_OPERATION_TOKEN: "refresh_operation_token",
    SEARCH_JOBS_BY_START_DATE: "search_jobs_by_start_date",
    GET_CUSTOM_FUNCTIONS: "get_custom_functions",
    GET_CUSTOM_FUNCTION: "get_custom_function",
    DROP_CUSTOM_FUNCTION: "drop_custom_function",
    DEPLOY_CUSTOM_FUNCTION_PROJECT: "deploy_custom_function_project",
    ADD_CUSTOM_FUNCTION_PROJECT: "add_custom_function_project",
    PACKAGE_CUSTOM_FUNCTION_PROJECT: "package_custom_function_project",
    RESTART:"restart",
    RESTART_SERVICE:"restart_service",
    GET_CONFIGUATION:
    "get_configuation"
};

export interface Operations{
    SQL: string;
    SYSTEM_INFORMATION: string,
    CLUSTER_STATUS: string,
    ADD_NODE: string,
    UPDATE_NODE: string,
    REMOVE_NODE: string,
    DESCRIBE_ALL: string,
    CREATE_SCHEMA: string,
    DESCRIBE_SCHEMA: string,
    DROP_SCHEMA: string,
    CREATE_TABLE: string,
    DESCRIBE_TABLE: string,
    DROP_TABLE: string,
    SEARCH_BY_VALUE: string,
    SEARCH_BY_HASH: string,
    SEARCH_BY_CONDITIONS: string,
    CSV_DATA_LOAD: string,
    CSV_URL_LOAD: string,
    CSV_FILE_LOAD: string,
    INSERT: string,
    UPDATE: string,
    DELETE: string,
    IMPORT_FROM_S3: string,
    EXPORT_TO_S3:string,
    EXPORT_LOCAL: string,
    ADD_USER: string,
    ALTER_USER: string,
    DROP_USER: string,
    LIST_USERS: string,
    LIST_ROLES: string,
    ALTER_ROLE: string,
    ADD_ROLE: string,
    READ_TRANSACTION_LOG: string,
    DELETE_TRANSACTION_LOGS:string,
    DELETE_RECORDS_BEFORE: string,
    READ_LOG: string,
    GET_JOB: string,
    CREATE_AUTHENTICATION_TOKENS: string,
    REFRESH_OPERATION_TOKEN: string,
    SEARCH_JOBS_BY_START_DATE:string,
    GET_CUSTOM_FUNCTIONS: string,
    GET_CUSTOM_FUNCTION: string,
    DROP_CUSTOM_FUNCTION: string,
    DEPLOY_CUSTOM_FUNCTION_PROJECT:string,
    ADD_CUSTOM_FUNCTION_PROJECT: string,
    PACKAGE_CUSTOM_FUNCTION_PROJECT: string,
    RESTART:string,
    RESTART_SERVICE:string,
    GET_CONFIGUATION:
    string;
};


export default operations;